version: "3"

services:
  php:
    build:
      context: ./php
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
